const express = require('express')
const { Router } = express
const router = Router()
const { signUp, logIn, logOut, getAllUsers, updateUserById, deleteUserById } = require('../controllers/auth.controllers')
const { getAllPhotos, createPhoto, deletePhotoById, updatePhotoById } = require('../controllers/gallery.controllers')
const { getClientOrders, getAllOrders, deleteOrderById, updateOrderById } = require('../controllers/order.controllers')
const { getAllProducts, createProduct, updateProductById, deleteProductById } = require('../controllers/products.controllers')
const { isAuthenticated, fadeLogs, isAdmin } = require('../middlewares/middlewares')
const upload = require('../libs/multer')

router
.get('/login', fadeLogs, (req, res) => { res.render('account/login', { user: req.session.user }) })
.get('/signup', fadeLogs, (req, res) => { res.render('account/signup', { user: req.session.user }) })
.get("/logout", logOut)
.get('/', isAuthenticated, getClientOrders)
.get('/administrador/ordenes', [ isAdmin, isAuthenticated ], getAllOrders)
.get('/administrador/ordenes/remover/:id', [ isAdmin, isAuthenticated ], deleteOrderById)
.post('/administrador/ordenes/editar/:id', [ isAdmin, isAuthenticated ], updateOrderById)
.get('/administrador/usuarios', [ isAdmin, isAuthenticated ], getAllUsers)
.get('/administrador/usuarios/remover/:id', [ isAdmin, isAuthenticated ], deleteUserById)
.post('/administrador/usuarios/editar/:id', [ isAdmin, isAuthenticated ], updateUserById)
.get('/administrador/productos', [ isAdmin, isAuthenticated ], getAllProducts)
.get('/administrador/productos/remover/:id', [ isAdmin, isAuthenticated ], deleteProductById)
.post('/administrador/productos', [ isAdmin, isAuthenticated, upload.single('image') ], createProduct)
.post('/administrador/productos/editar/:id', [ isAdmin, isAuthenticated, upload.single('image') ], updateProductById)
.get('/administrador/galeria', [ isAdmin, isAuthenticated ], getAllPhotos)
.get('/administrador/galeria/remover/:id', [ isAdmin, isAuthenticated ], deletePhotoById)
.post('/administrador/galeria', [ isAdmin, isAuthenticated, upload.single('image') ], createPhoto)
.post('/administrador/galeria/editar/:id', [ isAdmin, isAuthenticated, upload.single('image') ], updatePhotoById)
.post('/signup', signUp)
.post('/login', logIn)

module.exports = router